### ISSUE TITLE
[RFC] Tool filtering feature in MCP server

### ISSUE THREAD

**Issue by nathaliellenaa** [opensearch-project/opensearch-mcp-server-py#37]
# Background
Users may only need access to specific subsets of OpenSearch APIs, and loading and exposing all available tools can be overwhelming and leads to hallucinations. As we continue to add more tools to the OpenSearch MCP server, this issue will become more significant. We need a way to allow users to selectively enable tools based on their requirements.

# Proposed Options

## Option 1 - Tool filtering through a YAML file

Users need to parse the path to a config YAML file in the command when initiating the server, for example:
```
# For stdio
python -m mcp_server_opensearch --filter /path/to/config.yaml

# For SSE
python -m mcp_server_opensearch --transport sse --filter /path/to/config.yaml
```
The content of the config YAML file might include:
```
# Users can create their own category
tool_category:
  critical:
    - ListIndexTool
    - IndexMappingTool

tool_filters:
    # Enable specific API categories
    enabled_categories:
    - critical # This is a custom category created by users
    - search # Enable all search-related tools
    - cat # Enable all cat API tools
    
    # Enable specific tools by name
    enabled_tools:
    - SearchTool
    - CatIndicesTool
    
    # Disable specific tools by name
    disabled_tools:
    - BulkTool
    
    # Additional configuration -> Future enhancement (we can test it out with the above settings first)
    settings:
    - read_only: true # Enable GET endpoints only
    - write_only: true # Enable POST/PUT endpoints only
```
**Pros:**
* Structured and easy to maintain
* Can include detailed configurations
* Can be shared or re-used across deployments

**Cons:**
* Requires file management
    * Need to handle file parsing errors

## Option 2 - Tool filtering through environment variables

Users can set environment variables to filter the tools, for example:
```
# Environment setup
export OPENSEARCH_TOOL_CATEGORIES='{"<name of category>":["ListIndexTool","MsearchTool"]}'
export OPENSEARCH_ENABLED_CATEGORIES="search,cat"
export OPENSEARCH_ENABLED_TOOLS="SearchTool,CatIndicesTool"
export OPENSEARCH_DISABLED_TOOLS="BulkTool" 
export OPENSEARCH_SETTINGS_READ_ONLY=true
export OPENSEARCH_SETTINGS_WRITE_ONLY=true
```

**Pros:**
* No file management needed
    * No file permission issues
* Follow more standard MCP server implementation

**Cons:**
* Less readable for complex setup
* Cannot be re-used or shared across deployments
* Easy to mess up since there is no "schema" being followed
* Might have a limit of the env variables length
